### ISSUE TITLE
Restore view state?

### ISSUE THREAD

**Issue by doxxx** [joshuafcole/recall#12]
Is it possible to restore the view state as well? For example, that the Workspace tree is visible.

**Comment by joshuafcole** [comment]
Not yet, but it should be possible. The reason I don't have it added
currently is because there is a behavior for starting LT with the workspace
is open, so rather than just opening it if it was opened last, I'd need to
actually detect whether it was open. In the long term, I would like to
supply a generic way to toggle arbitrary non-file-backed features such as
the workspace or plugins.

On Mon, Jan 27, 2014 at 11:53 AM, Gordon Tyler notifications@github.comwrote:

> Is it possible to restore the view state as well? For example, that the
> Workspace tree is visible.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joshuafcole/recall/issues/12
> .

## 

Screw the environment. Please print this email immediately. And then burn
it.

**Comment by doxxx** [comment]
I see. Thanks for the info about that behavior to open the workspace on startup. That's doing the job for me. :)
